keda:
  enabled: true
  triggers:
    - type: azure-servicebus
      metadata:
        queueName: "notify_queue"
        connectionFromEnv: NOTIFY_QUEUE_CONNECTION_NAME
        messageCount: "5"

externalSecret:
  enabled: true
  refreshInterval: 1h
  secrets:
    - secretKey: TRADE_PLATFORM_CLIENT_SECRET
      remoteKey: tradePlatformClientSecret
    - secretKey: TRADE_PLATFORM_SUBSCRIPTION_KEY
      remoteKey: tradePlatformSubscriptionKey
    - secretKey: NOTIFY_QUEUE_CONNECTION_NAME
      remoteKey: serviceBusConnectionString

resources:
  limits:
    cpu: "2"
    memory: 4Gi
  requests:
    cpu: "500m"
    memory: 1Gi

config:
  NOTIFY_QUEUE_NAME: "notify_queue"
  ENABLE_EMAIL_NOTIFICATION: "true"
  ENABLE_TEXT_NOTIFICATION: "true"
  TRADE_PLATFORM_NOTIFY_URL: "https://internal-gateway.trade.defra.gov.uk/trade-notify/v1"
  TRADE_PLATFORM_SYSTEM_NAME: "IPAFFS"
  TRADE_PLATFORM_SYSTEM_UNIQUE_ID: "38BC514D-FC26-47BF-99C2-6FCACF581AF5"
  API_VERSION: "1.0.0"
  KEDA_MAX_MESSAGES: "100"
  KEDA_RECEIVE_WAIT_SECONDS: "10"
  KEDA_MAX_EMPTY_RECEIVES: "3"
