trigger:
  branches:
    include:
      - "*"

pool:
  name: 'DEFRA-COMMON-UBUNTU-SSV5'

resources:
  repositories:
    - repository: ipaffs-infra
      type: github
      endpoint: DEFRA
      name: DEFRA/ipaffs-infra
      ref: refs/heads/main

    - repository: ipaffs-manifest
      type: github
      endpoint: DEFRA
      name: DEFRA/ipaffs-manifest
      ref: refs/heads/master

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    values:
      - DEV
      - TST
      - PRE
      - PRD
    default: DEV

variables:
  - group: "${{ parameters.environmentName }}"
  - name: serviceName
    value: notify-service

stages:
  - template: /pipelines/templates/java-template.yaml@ipaffs-infra
    parameters:
      environmentName: "${{ parameters.environmentName }}"
      serviceName: "${{ variables.serviceName }}"
      dockerFile: Dockerfile
      sonarAnalysis: true
      sonarReferenceBranch: master
