service: notify-service

container:
  replicas: 1

config:
  JDK_JAVA_OPTIONS: "-XX:MaxRAMPercentage=60.0"

resources:
  requests:
    cpu: 250m
    memory: 700Mi
  limits:
    cpu: 2
    memory: 700Mi

serviceBus:
  enabled: true
  connectionStringSecretKey: NOTIFY_QUEUE_CONNECTION_NAME

keda:
  enabled: true
  pollingInterval: 30
  maxReplicaCount: 1
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

externalSecret:
  enabled: true
  refreshInterval: 1h
  secrets:
    - secretKey: TRADE_PLATFORM_CLIENT_SECRET
      remoteKey: tradePlatformClientSecret
    - secretKey: TRADE_PLATFORM_SUBSCRIPTION_KEY
      remoteKey: tradePlatformSubscriptionKey
